# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_device.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogAddDevice(object):
    def setupUi(self, DialogAddDevice):
        DialogAddDevice.setObjectName("DialogAddDevice")
        DialogAddDevice.resize(844, 72)
        self.gridLayout = QtWidgets.QGridLayout(DialogAddDevice)
        self.gridLayout.setObjectName("gridLayout")
        self.labelDevice = QtWidgets.QLabel(DialogAddDevice)
        self.labelDevice.setObjectName("labelDevice")
        self.gridLayout.addWidget(self.labelDevice, 0, 0, 1, 1)
        self.labelType = QtWidgets.QLabel(DialogAddDevice)
        self.labelType.setObjectName("labelType")
        self.gridLayout.addWidget(self.labelType, 0, 1, 1, 1)
        self.labelHWaddress = QtWidgets.QLabel(DialogAddDevice)
        self.labelHWaddress.setObjectName("labelHWaddress")
        self.gridLayout.addWidget(self.labelHWaddress, 0, 2, 1, 1)
        self.labelComPort = QtWidgets.QLabel(DialogAddDevice)
        self.labelComPort.setObjectName("labelComPort")
        self.gridLayout.addWidget(self.labelComPort, 0, 3, 1, 1)
        self.labelSyringe = QtWidgets.QLabel(DialogAddDevice)
        self.labelSyringe.setObjectName("labelSyringe")
        self.gridLayout.addWidget(self.labelSyringe, 0, 4, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogAddDevice)
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 0, 6, 2, 1)
        self.comboBoxDevice = QtWidgets.QComboBox(DialogAddDevice)
        self.comboBoxDevice.setCurrentText("")
        self.comboBoxDevice.setObjectName("comboBoxDevice")
        self.comboBoxDevice.addItem("")
        self.comboBoxDevice.addItem("")
        self.comboBoxDevice.addItem("")
        self.gridLayout.addWidget(self.comboBoxDevice, 1, 0, 1, 1)
        self.comboBoxDeviceType = QtWidgets.QComboBox(DialogAddDevice)
        self.comboBoxDeviceType.setObjectName("comboBoxDeviceType")
        self.gridLayout.addWidget(self.comboBoxDeviceType, 1, 1, 1, 1)
        self.comboBoxHWaddress = QtWidgets.QComboBox(DialogAddDevice)
        self.comboBoxHWaddress.setObjectName("comboBoxHWaddress")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.comboBoxHWaddress.addItem("")
        self.gridLayout.addWidget(self.comboBoxHWaddress, 1, 2, 1, 1)
        self.comboBoxCOMport = QtWidgets.QComboBox(DialogAddDevice)
        self.comboBoxCOMport.setObjectName("comboBoxCOMport")
        self.gridLayout.addWidget(self.comboBoxCOMport, 1, 3, 1, 1)
        self.comboBoxSyringe = QtWidgets.QComboBox(DialogAddDevice)
        self.comboBoxSyringe.setObjectName("comboBoxSyringe")
        self.gridLayout.addWidget(self.comboBoxSyringe, 1, 4, 1, 1)
        self.checkBoxHiRes = QtWidgets.QCheckBox(DialogAddDevice)
        self.checkBoxHiRes.setObjectName("checkBoxHiRes")
        self.gridLayout.addWidget(self.checkBoxHiRes, 1, 5, 1, 1)

        self.retranslateUi(DialogAddDevice)
        self.comboBoxDevice.setCurrentIndex(-1)
        self.buttonBox.accepted.connect(DialogAddDevice.accept)
        self.buttonBox.rejected.connect(DialogAddDevice.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogAddDevice)

    def retranslateUi(self, DialogAddDevice):
        _translate = QtCore.QCoreApplication.translate
        DialogAddDevice.setWindowTitle(_translate("DialogAddDevice", "Add Device"))
        self.labelDevice.setText(_translate("DialogAddDevice", "Device"))
        self.labelType.setText(_translate("DialogAddDevice", "Type"))
        self.labelHWaddress.setText(_translate("DialogAddDevice", "HW Address"))
        self.labelComPort.setText(_translate("DialogAddDevice", "COM port"))
        self.labelSyringe.setText(_translate("DialogAddDevice", "Syringe"))
        self.comboBoxDevice.setItemText(0, _translate("DialogAddDevice", "PSD/4"))
        self.comboBoxDevice.setItemText(1, _translate("DialogAddDevice", "PSD/6"))
        self.comboBoxDevice.setItemText(2, _translate("DialogAddDevice", "MVP/4"))
        self.comboBoxHWaddress.setItemText(0, _translate("DialogAddDevice", "0"))
        self.comboBoxHWaddress.setItemText(1, _translate("DialogAddDevice", "1"))
        self.comboBoxHWaddress.setItemText(2, _translate("DialogAddDevice", "2"))
        self.comboBoxHWaddress.setItemText(3, _translate("DialogAddDevice", "3"))
        self.comboBoxHWaddress.setItemText(4, _translate("DialogAddDevice", "4"))
        self.comboBoxHWaddress.setItemText(5, _translate("DialogAddDevice", "5"))
        self.comboBoxHWaddress.setItemText(6, _translate("DialogAddDevice", "6"))
        self.comboBoxHWaddress.setItemText(7, _translate("DialogAddDevice", "7"))
        self.comboBoxHWaddress.setItemText(8, _translate("DialogAddDevice", "8"))
        self.comboBoxHWaddress.setItemText(9, _translate("DialogAddDevice", "9"))
        self.comboBoxHWaddress.setItemText(10, _translate("DialogAddDevice", "A"))
        self.comboBoxHWaddress.setItemText(11, _translate("DialogAddDevice", "B"))
        self.comboBoxHWaddress.setItemText(12, _translate("DialogAddDevice", "C"))
        self.comboBoxHWaddress.setItemText(13, _translate("DialogAddDevice", "D"))
        self.comboBoxHWaddress.setItemText(14, _translate("DialogAddDevice", "E"))
        self.comboBoxHWaddress.setItemText(15, _translate("DialogAddDevice", "F"))
        self.checkBoxHiRes.setText(_translate("DialogAddDevice", "Hi res mode"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogAddDevice = QtWidgets.QDialog()
    ui = Ui_DialogAddDevice()
    ui.setupUi(DialogAddDevice)
    DialogAddDevice.show()
    sys.exit(app.exec_())
